### ISSUE TITLE
serf doesn't start on CentOS 7 with dhcp

### ISSUE THREAD

**Issue by yyamano** [bbaugher/serf#30]
On a CentOS 7 host with dhcp, /etc/init.d/serf fails at a boot time with the following message in /opt/serf/logs/serf.log.

> ==> Interface 'enp0s8' has no addresses

After the boot, it works fine via service command.

I have an interface option in /opt/serfconfig/serf_agent.json.

> "interface": "enp0s8"

I guess the problem is start order of startup scripts.
/etc/init.d/serf could be started before getting IP address.
Adding runtime dependencies	to /etc/init.d/serf as	bellow makes it work to me.

>  # Required-Start: network
>  # Required-Stop: network

What do	you think adding them to serf/templates/default/serf_service.erb?
Also making the	dependencies configurable should be work to me.

**Comment by bbaugher** [comment]
Does this https://github.com/bbaugher/serf/commit/4863c4e1f19d108c0f5c9dbcd04810f31a1803cb work for you?

**Comment by yyamano** [comment]
Thank you for the quick fix, it works fine to me.
